CREATE TABLE CATEGORY(ID IDENTITY NOT NULL PRIMARY KEY, CATEGORY_NAME VARCHAR NOT NULL);
INSERT INTO CATEGORY(CATEGORY_NAME) VALUES('Supermercado');
INSERT INTO CATEGORY(CATEGORY_NAME) VALUES('Farmácia');
INSERT INTO CATEGORY(CATEGORY_NAME) VALUES('Restaurantes');
INSERT INTO CATEGORY(CATEGORY_NAME) VALUES('Estacionamento');
INSERT INTO CATEGORY(CATEGORY_NAME) VALUES('Aliexpress');
INSERT INTO CATEGORY(CATEGORY_NAME) VALUES('Amazon Prime');